### ISSUE TITLE
styling the timer

### ISSUE THREAD

**Issue by wibiesana** [aneeshikmat/yii2-time-down-counter#5]
how can i use my own style ?, i always failed to use my own style like i put in h3 tag

**Comment by aneeshikmat** [comment]
Hi wibiesana, 

I think you miss to set a truth id selector for timer, you most specify tag with default id or define your new id. 

Look at this example: 
```
`<?php
    use aneeshikmat\yii2\Yii2TimerCountDown\Yii2TimerCountDown;
?>
<h3 id="time-down-counter"></h3>
<?= Yii2TimerCountDown::widget([
    'countDownDate' => strtotime('+1 minutes') * 1000,// You most * 1000 to convert time to milisecond
    'addSpanForResult' => false,
    'addSpanForEachNum' => false,
]) ?>
````

Keep note if you need to change id you can use this option in widget: 
`'countDownIdSelector' => 'your-id',`

Also Keep note to set: addSpanForResult & addSpanForEachNum as a true if you need to put span for each number in timer, and this span cant be changed to new tag.
